################################################################################
# This config file is meant for settings that affect the whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.


################################################################################
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
version: 0.7.5
name: Mech
title: Mech
owner: Mech Project
email: german.mb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Easy command line virtual machines for VMWare
baseurl: /mech # the subpath of your site, e.g. /blog
url: https://mechboxes.github.io
repository: https://github.com/mechboxes/mech
docs_branch: gh-pages
github_username:  mechboxes
disqus_shortname: mechboxes

theme_color_light: "#bfdd97"
theme_color_dark: "#8fc44a"
theme_color_quickstart: "#689137"

logo: "/img/logo-2x.png"
logo_width: 221
logo_height: 251

google_analytics_id: UA-7630729-5
# google_site_verification: google_site_verification_key
# docsearch_name: Kronuz
# docsearch_key: 00000000000000000000000000000000

################################################################################
# Build settings
markdown: kramdown

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true

defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
  - scope:
      path: _posts
      type: posts
    values:
      layout: news_item
      image: "/img/twitter-card.png"

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

sass:
  style: compressed

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - icomoon-selection.json
  - readme.md
  - CNAME
